---
title: "Análise de sobrevivência de idosos portadores de doença renal crônica em hemodiálise: estudo restrospectivo com dados do Registro de Diálise e Transplante Austríaco"
author: "**Karla de Araujo Ferreira**"
lang: pt
format:
    pdf: default
    html: 
      self-contained: true
csl: epidemiology.csl
bibliography: references.bib
---

**Programa de Pós-Graduação Stricto-Sensu em Epidemiologia em Saúde Pública, Escola Nacional de Saúde Pública Sergio Arouca, Fundação Oswaldo Cruz. Rio de Janeiro, fevereiro de 2023.**

**Disciplina: Introdução à Análise de Sobrevivência - 2023**

\newpage

```{r pacotes, include=FALSE, message=FALSE, warning=FALSE}
#instalar e carregar pacotes
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  here, #caminho do projeto
  readxl, #ler arquivo excel
  tableone, #fazer tabela 1
  kableExtra,#renderizar tabela
  knitr, #renderizar tabela
  survival, #analise de sobrevivencia
  survminer,#plotar graficos KM
  ggsurvfit,
  gtsummary, # tabela OR e IC 
  tidycmprsk, 
  condsurv,
  patchwork, #compor graficos ggplot
  finalfit, #checar dados faltantes
  tidyverse,
  ResourceSelection, #qualidade do ajuste
  ggplot2,
  gridExtra, # forest plot OR e IC 
  equatiomatic #escrever equacoes 
  )

```

```{r banco, include=FALSE, message=FALSE, warning=FALSE}
# 0. Leitura do banco de dados

#ler banco de dados
data<-readxl::read_excel(here::here("data.xlsx"), sheet = "publicData")
#estrutura do banco
str(data)

```

```{r organiza, include=FALSE, message=FALSE, warning=FALSE}
#1. Organizar banco
#transformar covariaveis em fator e idade em valor 
data<-cbind(lapply(data[,1:10],as.factor), (data[,11:13]))
data$idade<-round(data$age10*10,0)

str(data)

#Apenas pacientes em dialise
data<-subset(data,dialysis == 1 )


```

```{r tab1,include=FALSE, message=FALSE, warning=FALSE}
#Análise exploratória
# Tabela 1

#normalidade - idade
hist(data$idade)
#nao e normalmente distribuida

tab1 <- tableone::CreateTableOne(vars = c("Gender","DM","hypert",
                                "heart","","neoplasia",
                                "liver","vascular","COPD",
                                "idade"), 
                                strata = "dead",test = TRUE,                                       includeNA = TRUE, data = data)

tabela1<-print (tab1, showAllLevels = TRUE,nonnormal = "idade")

tabela1<-tabela1[,1:3]

tabela1[,1]<-ifelse(tabela1[,1] == "0", "Não", tabela1[,1] )
tabela1[,1]<-ifelse(tabela1[,1] == "1", "Sim", tabela1[,1] )

tabela1<- as.data.frame(tabela1)

tabela1$variav<-c("N","Sexo(%)","",
                      "Diabetes mellitus (%)","","Hipertensão (%)",
                      "","Doença coração(%)","",
                      "Neoplasia (%)", "","Doença hepática (%)",
                      "","Doença vascular (%)", "",
                      "DPOC (%)", "", "Idade (mediana [IQR])")


tabela1<-data.frame(tabela1[,c(4,1,2,3)])

colnames(tabela1)<-c("Característica","", "Não óbito", "Óbito")

rownames(tabela1) <- NULL
```


```{r Tabela1}
#| label: tbl-Tabela1
#| tbl-cap: "Características da coorte de idosos que iniciaram hemodiálise entre 2002 e 2009, segundo status (óbito)."
#| warning: false
#| echo: false
#| message: false

kbl(tabela1, align = "lcccc") %>%
kable_classic(full_width = F) %>%
footnote(symbol = "DPOC: Doença pulmonar obstrutiva crônica"
)
```

\newpage


```{r KMglobal}
#Status nao pode ser fator!
data$dead<-as.numeric(data$dead)

#Objeto surival
y <- survival::Surv(data$Time_to_Event, data$dead)

#Kaplan-Meier plot
survfit2(y ~ 1, data = data) %>% 
  ggsurvfit() +
  labs(
    x = "Anos",
    y = "Probabilidade de sobrevivência"
  ) +
  add_confidence_interval() +
  add_risktable() 

```

```{r}
#Probabilidde de sobreviver pelo menos 1, 2, ..., 8 anos
summary(survfit(y ~ 1, data = data), times = c(1:8))
#ou
#survfit(Surv(Time_to_Event, dead) ~ 1, data = data) %>% 
#  gtsummary::tbl_survfit(
#    times = c(1,2,3,4,5),
#    label_header = "**survival (95% CI)**"
# )

#Mediana = 2.24 anos (2.15,2.33)
survfit(Surv(Time_to_Event, dead) ~ 1, data = data)
```


```{r KMestrat}

#Kaplan-Meier plot - estratificado
#Sexo

splots <- list()
splots[[1]] <- ggsurvplot(survfit(y ~ Gender, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("F", "M"), legend.title="Sexo",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

#DM
splots[[2]] <- ggsurvplot(survfit(y ~ DM, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title="Diabetes mellitus",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

#Hipertensao
splots[[3]] <- ggsurvplot(survfit(y ~ hypert, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title="Hipertensão",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 
#Coracao
splots[[4]] <- ggsurvplot(survfit(y ~ heart, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title="Doença coração",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

#Neoplasia
splots[[5]] <- ggsurvplot(survfit(y ~ neoplasia, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title="Neoplasia",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 
 
#Figado
splots[[6]] <- ggsurvplot(survfit(y ~ liver, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title="Doença hepática",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

#Vascular
splots[[7]] <- ggsurvplot(survfit(y ~ vascular, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title=" Doença vascular",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

#DPOC
splots[[8]] <- ggsurvplot(survfit(y ~ COPD, data = data), data = data,conf.int=F, pval=TRUE, risk.table= FALSE, 
           legend.labs=c("Não", "Sim"), legend.title=" DPOC",  
           ggtheme = theme_minimal(),
           xlab = "Anos", ylab = "S(t)") 

# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(splots, print = TRUE, ncol = 1, nrow = 1)

```


```{r logrank}
#Comparando grupos - Log-rank
#Sexo
survdiff(y ~ Gender, data = data)
#Não há diferença 

#DM
survdiff(y ~ DM, data = data)
#Diferença significativa p= 0.04

#Hipertensao
survdiff(y ~ hypert, data = data)
#Diferença significativa p= <2e-16 

#Coraçao
survdiff(y ~ heart, data = data)
#Não há diferença 

#Neoplasia
survdiff(y ~ neoplasia, data = data)
#Não há diferença 

#Figado
survdiff(y ~ liver, data = data)
##Diferença significativa p= 0.01

#Vascular
survdiff(y ~ vascular, data = data)
#Não há diferença 

#DPOC
survdiff(y ~ COPD, data = data)
#Diferença significativa p= 8e-04

```


```{r peto}
#Comparando grupos - Log-rank
#Sexo
survdiff(y ~ Gender, data = data, rho=1)
#Não há diferença 

#DM
survdiff(y ~ DM, data = data, rho=1)
#Diferença significativa p= 0.04

#Hipertensao
survdiff(y ~ hypert, data = data, rho=1)
#Diferença significativa p= <2e-16 

#Coraçao
survdiff(y ~ heart, data = data, rho=1)
#Não há diferença 

#Neoplasia
survdiff(y ~ neoplasia, data = data, rho=1)
#Não há diferença 

#Figado
survdiff(y ~ liver, data = data, rho=1)
##Diferença significativa p= 0.01

#Vascular
survdiff(y ~ vascular, data = data, rho=1)
#Não há diferença 

#DPOC
survdiff(y ~ COPD, data = data, rho=1)
#Diferença significativa p= 8e-04

```


```{r Cox_simples}

#Efeito isolado de cada covariavel sobre o tempo de sobrevivencia
#significancia p < 0.2

#Sexo
coxph(y ~ Gender, data = data) %>%
tbl_regression(exp = TRUE) 
#nao signifitiva

#Idade
coxph(y ~ idade, data = data) %>%
tbl_regression(exp = TRUE) 
#nao signifitiva


#DM
cox_dm <- coxph(y ~ DM, data = data) %>%
tbl_regression(exp = TRUE) 
#signifitiva

#hipertensao
coxph(y ~ hypert, data = data) %>%
tbl_regression(exp = TRUE) 
#signifitiva

#Coracao
coxph(y ~ heart, data = data) %>%
tbl_regression(exp = TRUE) 
#nao signifitiva

#Neoplasia
coxph(y ~ neoplasia, data = data) %>%
tbl_regression(exp = TRUE) 
#nao signifitiva

#Figado
coxph(y ~ liver, data = data) %>%
tbl_regression(exp = TRUE) 
#signifitiva

#Vascular
coxph(y ~ vascular, data = data) %>%
tbl_regression(exp = TRUE) 
#signifitiva p < 0.122

#DPOC
coxph(y ~ COPD, data = data) %>%
tbl_regression(exp = TRUE) 
#signifitiva

#os modelos de Cox simples confirmam a analise grafica e teste log-rak e peto

```


```{r cox_multiplo}
#Efeitos ajustados das covariaveis sobre o tempo de sobrevivencia


m1<- coxph(y ~ Gender + idade, x= TRUE, data = data) 
m2<- coxph(y ~ Gender + idade + DM, x= TRUE, data = data) 
m3<- coxph(y ~ Gender + idade + DM + hypert, x= TRUE, data = data) 
m4<- coxph(y ~ Gender + idade + DM + hypert + liver, x= TRUE, data = data)
m5<- coxph(y ~ Gender + idade + DM + hypert + liver + vascular, x= TRUE, 
           data = data)
m6<- coxph(y ~ Gender + idade + DM + hypert + liver + vascular + COPD, 
           x= TRUE, data = data) 

anova(m1, m2, m3, m4, m5, m6)

summary(m6)

```


```{r}
#Resultados do modelo ajustado

m6 %>%
tbl_regression(exp = TRUE) 

```

```{r}
#Indice prognostico

source("Rfun.r")
par(mfrow = c(2,2))
plot.pi(m3, main = "Modelo 3" )
plot.pi(m4, main = "Modelo 4" )
plot.pi(m5, main = "Modelo 5" )
plot.pi(m6, main = "Modelo 6" )

```
```{r}
#Analise de residuos

#Proporcionalidade
res <- cox.zph(m6)
plot(res, xlab = "Anos", resid= FALSE)

m6.sch <- cox.zph(m6)
m6.sch
#log-linearidade
#pontos atípicos e influentes

ggcoxzph(res)

```


